export const COLORS = {
  red: "red",
  blue: "blue",
  yellow: "yellow",
  green: "green",
  white: "#fff",
  ligthOrangeIcon: "#FCDAC2",
  darkOrangeIcon: "#FEA31C",
  ligthBlueIcon: "#DBE9FD",
  darkBlueIcon: "#0958C5",
  ligthGreenIcon: "#D7FCD6",
  darkGreenIcon: "#18966D",
  ligthRedIcon: "#FFC2C3",
  darkRedIcon: "#EA3A3D",
  ligthPurpleIcon: "#D8D7F8",
  darkPurpleIcon: "#9365E6",
  ligthCyanIcon: "#D8F7FF",
  darkCyanIcon: "#1FB3D7",
  lightCurrentIcon: "#FEF1DE",
  darkCurrentIcon: "#FDD888",
};
